server:
  port: 8080

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      # 采用匹配模式
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/${mysql.database}?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: ${mysql.username}
    password: ${mysql.password}


mybatis-plus:
  type-aliases-package: com.miniblog.pojo.po
  configuration:
    map-underscore-to-camel-case: true